[package]
name = "vexview-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-opener = "2"
serde = { workspace = true }
serde_json = { workspace = true }
vex-core = { workspace = true }
vex-image = { workspace = true }
vex-video = { workspace = true }
vex-edit = { workspace = true }
image = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
base64 = "0.22"
rfd = "0.15"
arboard = "3"
tauri-runtime = "2"
lru = { workspace = true }
