[package]
name = "vex-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
gtk = ["dep:gtk4", "dep:libadwaita"]

[dependencies]
vex-core.workspace = true
vex-image.workspace = true
vex-video.workspace = true
vex-edit.workspace = true
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true

gtk4 = { version = "0.9", optional = true }
libadwaita = { version = "0.7", optional = true }

[[bin]]
name = "vexview"
path = "src/main.rs"
