[package]
name = "vex-edit"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
vex-core.workspace = true
vex-image.workspace = true
image.workspace = true
imageproc.workspace = true
fast_image_resize.workspace = true
thiserror.workspace = true
log.workspace = true
serde.workspace = true
